windows: Fix build
I'm not sure why, but having the definitions in the headers causes a
multiple definition error:

/usr/lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld: brokerapp.cpp.obj (symbol from plugin):(.gnu.linkonce.t._ZNK3shv6broker3rpc24ClientConnectionOnBroker12connectionIdEv[_ZThn16_NK3shv6broker3rpc24ClientConnectionOnBroker12connectionIdEv]+0x0): multiple definition of `shv::broker::rpc::ClientConnectionOnBroker::connectionId() const'; mocs_compilation.cpp.obj (symbol from plugin):(.gnu.linkonce.t._ZNK3shv6broker3rpc24ClientConnectionOnBroker12connectionIdEv[_ZThn408_NK3shv6broker3rpc24ClientConnectionOnBroker12connectionIdEv]+0x0): first defined here
/usr/lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld: brokerapp.cpp.obj (symbol from plugin):(.gnu.linkonce.t._ZNK3shv6broker3rpc24ClientConnectionOnBroker12connectionIdEv[_ZThn16_NK3shv6broker3rpc24ClientConnectionOnBroker12connectionIdEv]+0x0): multiple definition of `non-virtual thunk to shv::broker::rpc::ClientConnectionOnBroker::connectionId() const'; mocs_compilation.cpp.obj (symbol from plugin):(.gnu.linkonce.t._ZNK3shv6broker3rpc24ClientConnectionOnBroker12connectionIdEv[_ZThn408_NK3shv6broker3rpc24ClientConnectionOnBroker12connectionIdEv]+0x0): first defined here
/usr/lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld: brokerapp.cpp.obj (symbol from plugin):(.gnu.linkonce.t._ZNK3shv6broker3rpc24ClientConnectionOnBroker12connectionIdEv[_ZThn16_NK3shv6broker3rpc24ClientConnectionOnBroker12connectionIdEv]+0x0): multiple definition of `non-virtual thunk to shv::broker::rpc::ClientConnectionOnBroker::connectionId() const'; mocs_compilation.cpp.obj (symbol from plugin):(.gnu.linkonce.t._ZNK3shv6broker3rpc24ClientConnectionOnBroker12connectionIdEv[_ZThn408_NK3shv6broker3rpc24ClientConnectionOnBroker12connectionIdEv]+0x0): first defined here